/**
 * Flowtype definitions for index
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.6.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

declare module "csv-parser" {
  import type { Transform } from "stream";

  declare type CsvParser = {} & Transform;

  declare interface CsvParserOptions {
    escape?: string;
    headers?: $ReadOnlyArray<string> | boolean;
    mapHeaders?: (args: {
      header: string,
      index: number
    }) => string | null;
    mapValues?: (args: {
      header: string,
      index: number,
      value: any
    }) => any;
    newline?: string;
    quote?: string;
    raw?: boolean;
    separator?: string;
    skipComments?: number | string;
    skipLines?: number;
    maxRowBytes?: number;
    strict?: boolean;
  }
  declare var csvParser: (
    optionsOrHeaders?: CsvParserOptions | $ReadOnlyArray<string>
  ) => CsvParser;
  declare module.exports: typeof csvParser;
}
