// flow-typed signature: 9b699448efd27a63f0bbdf0ad3d59e0a
// flow-typed version: <<STUB>>/csv-parser_v2.1.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csv-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csv-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'csv-parser/index' {
  declare module.exports: $Exports<'csv-parser'>;
}
declare module 'csv-parser/index.js' {
  declare module.exports: $Exports<'csv-parser'>;
}
