// flow-typed signature: 1bdf8c6403b211a5a7ec81fc6b5adaf1
// flow-typed version: <<STUB>>/js-to-mjs_v^0.2.0/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-to-mjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-to-mjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-to-mjs/src/find' {
  declare module.exports: any;
}

declare module 'js-to-mjs/src/util' {
  declare module.exports: any;
}

declare module 'js-to-mjs/test/fixtures/a/a' {
  declare module.exports: any;
}

declare module 'js-to-mjs/test/fixtures/a/export' {
  declare module.exports: any;
}

declare module 'js-to-mjs/test/fixtures/dynamic' {
  declare module.exports: any;
}

declare module 'js-to-mjs/test/fixtures/from/dynamic' {
  declare module.exports: any;
}

declare module 'js-to-mjs/test/fixtures' {
  declare module.exports: any;
}

declare module 'js-to-mjs/test/fixtures/no' {
  declare module.exports: any;
}

declare module 'js-to-mjs/test/fixtures/x' {
  declare module.exports: any;
}

declare module 'js-to-mjs/test/fixtures/y' {
  declare module.exports: any;
}

declare module 'js-to-mjs/test/fixtures/z/z' {
  declare module.exports: any;
}

declare module 'js-to-mjs/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-to-mjs/index' {
  declare module.exports: $Exports<'js-to-mjs'>;
}
declare module 'js-to-mjs/index.js' {
  declare module.exports: $Exports<'js-to-mjs'>;
}
declare module 'js-to-mjs/src/find.js' {
  declare module.exports: $Exports<'js-to-mjs/src/find'>;
}
declare module 'js-to-mjs/src/util.js' {
  declare module.exports: $Exports<'js-to-mjs/src/util'>;
}
declare module 'js-to-mjs/test/fixtures/a/a.js' {
  declare module.exports: $Exports<'js-to-mjs/test/fixtures/a/a'>;
}
declare module 'js-to-mjs/test/fixtures/a/export.js' {
  declare module.exports: $Exports<'js-to-mjs/test/fixtures/a/export'>;
}
declare module 'js-to-mjs/test/fixtures/dynamic.js' {
  declare module.exports: $Exports<'js-to-mjs/test/fixtures/dynamic'>;
}
declare module 'js-to-mjs/test/fixtures/from/dynamic.js' {
  declare module.exports: $Exports<'js-to-mjs/test/fixtures/from/dynamic'>;
}
declare module 'js-to-mjs/test/fixtures/index' {
  declare module.exports: $Exports<'js-to-mjs/test/fixtures'>;
}
declare module 'js-to-mjs/test/fixtures/index.js' {
  declare module.exports: $Exports<'js-to-mjs/test/fixtures'>;
}
declare module 'js-to-mjs/test/fixtures/no.js' {
  declare module.exports: $Exports<'js-to-mjs/test/fixtures/no'>;
}
declare module 'js-to-mjs/test/fixtures/x.js' {
  declare module.exports: $Exports<'js-to-mjs/test/fixtures/x'>;
}
declare module 'js-to-mjs/test/fixtures/y.js' {
  declare module.exports: $Exports<'js-to-mjs/test/fixtures/y'>;
}
declare module 'js-to-mjs/test/fixtures/z/z.js' {
  declare module.exports: $Exports<'js-to-mjs/test/fixtures/z/z'>;
}
declare module 'js-to-mjs/test/test.js' {
  declare module.exports: $Exports<'js-to-mjs/test/test'>;
}
