// flow-typed signature: cb3aae5727bb010adb26f226d91dd595
// flow-typed version: <<STUB>>/numeric_v^1.2.6/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'numeric'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'numeric' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'numeric/numeric-1.2.6' {
  declare module.exports: any;
}

declare module 'numeric/numeric-1.2.6.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'numeric/numeric-1.2.6.js' {
  declare module.exports: $Exports<'numeric/numeric-1.2.6'>;
}
declare module 'numeric/numeric-1.2.6.min.js' {
  declare module.exports: $Exports<'numeric/numeric-1.2.6.min'>;
}
