// flow-typed signature: df9bd80518ac4a02cf59fe292ae652c0
// flow-typed version: <<STUB>>/random-js_v2.1.0/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'random-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'random-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'random-js/dist/random-js.esm' {
  declare module.exports: any;
}

declare module 'random-js/dist/random-js.umd' {
  declare module.exports: any;
}

declare module 'random-js/dist/random-js.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'random-js/dist/random-js.esm.js' {
  declare module.exports: $Exports<'random-js/dist/random-js.esm'>;
}
declare module 'random-js/dist/random-js.umd.js' {
  declare module.exports: $Exports<'random-js/dist/random-js.umd'>;
}
declare module 'random-js/dist/random-js.umd.min.js' {
  declare module.exports: $Exports<'random-js/dist/random-js.umd.min'>;
}
