// flow-typed signature: 493785184846dd96f58e253a4c718616
// flow-typed version: <<STUB>>/string-to-stream_v^3.0.1/flow_v0.134.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-to-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-to-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'string-to-stream/index' {
  declare module.exports: $Exports<'string-to-stream'>;
}
declare module 'string-to-stream/index.js' {
  declare module.exports: $Exports<'string-to-stream'>;
}
