// flow-typed signature: d732e4f8d39a3e6d8db3fdeafd60e375
// flow-typed version: <<STUB>>/underscore-contrib_v^0.3.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'underscore-contrib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'underscore-contrib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'underscore-contrib/dist/underscore-contrib' {
  declare module.exports: any;
}

declare module 'underscore-contrib/dist/underscore-contrib.min' {
  declare module.exports: any;
}

declare module 'underscore-contrib/Gruntfile' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/array.builders' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/array.selectors' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/collections.walk' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/function.arity' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/function.combinators' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/function.dispatch' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/function.iterators' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/function.predicates' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/object.builders' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/object.selectors' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/util.existential' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/util.operators' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/util.strings' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/util.trampolines' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/vendor/jquery' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/vendor/jslitmus' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/vendor/qunit' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/vendor/runner' {
  declare module.exports: any;
}

declare module 'underscore-contrib/test/vendor/underscore' {
  declare module.exports: any;
}

declare module 'underscore-contrib/underscore.array.builders' {
  declare module.exports: any;
}

declare module 'underscore-contrib/underscore.array.selectors' {
  declare module.exports: any;
}

declare module 'underscore-contrib/underscore.collections.walk' {
  declare module.exports: any;
}

declare module 'underscore-contrib/underscore.function.arity' {
  declare module.exports: any;
}

declare module 'underscore-contrib/underscore.function.combinators' {
  declare module.exports: any;
}

declare module 'underscore-contrib/underscore.function.dispatch' {
  declare module.exports: any;
}

declare module 'underscore-contrib/underscore.function.iterators' {
  declare module.exports: any;
}

declare module 'underscore-contrib/underscore.function.predicates' {
  declare module.exports: any;
}

declare module 'underscore-contrib/underscore.object.builders' {
  declare module.exports: any;
}

declare module 'underscore-contrib/underscore.object.selectors' {
  declare module.exports: any;
}

declare module 'underscore-contrib/underscore.util.existential' {
  declare module.exports: any;
}

declare module 'underscore-contrib/underscore.util.operators' {
  declare module.exports: any;
}

declare module 'underscore-contrib/underscore.util.strings' {
  declare module.exports: any;
}

declare module 'underscore-contrib/underscore.util.trampolines' {
  declare module.exports: any;
}

// Filename aliases
declare module 'underscore-contrib/dist/underscore-contrib.js' {
  declare module.exports: $Exports<'underscore-contrib/dist/underscore-contrib'>;
}
declare module 'underscore-contrib/dist/underscore-contrib.min.js' {
  declare module.exports: $Exports<'underscore-contrib/dist/underscore-contrib.min'>;
}
declare module 'underscore-contrib/Gruntfile.js' {
  declare module.exports: $Exports<'underscore-contrib/Gruntfile'>;
}
declare module 'underscore-contrib/index' {
  declare module.exports: $Exports<'underscore-contrib'>;
}
declare module 'underscore-contrib/index.js' {
  declare module.exports: $Exports<'underscore-contrib'>;
}
declare module 'underscore-contrib/test/array.builders.js' {
  declare module.exports: $Exports<'underscore-contrib/test/array.builders'>;
}
declare module 'underscore-contrib/test/array.selectors.js' {
  declare module.exports: $Exports<'underscore-contrib/test/array.selectors'>;
}
declare module 'underscore-contrib/test/collections.walk.js' {
  declare module.exports: $Exports<'underscore-contrib/test/collections.walk'>;
}
declare module 'underscore-contrib/test/function.arity.js' {
  declare module.exports: $Exports<'underscore-contrib/test/function.arity'>;
}
declare module 'underscore-contrib/test/function.combinators.js' {
  declare module.exports: $Exports<'underscore-contrib/test/function.combinators'>;
}
declare module 'underscore-contrib/test/function.dispatch.js' {
  declare module.exports: $Exports<'underscore-contrib/test/function.dispatch'>;
}
declare module 'underscore-contrib/test/function.iterators.js' {
  declare module.exports: $Exports<'underscore-contrib/test/function.iterators'>;
}
declare module 'underscore-contrib/test/function.predicates.js' {
  declare module.exports: $Exports<'underscore-contrib/test/function.predicates'>;
}
declare module 'underscore-contrib/test/object.builders.js' {
  declare module.exports: $Exports<'underscore-contrib/test/object.builders'>;
}
declare module 'underscore-contrib/test/object.selectors.js' {
  declare module.exports: $Exports<'underscore-contrib/test/object.selectors'>;
}
declare module 'underscore-contrib/test/util.existential.js' {
  declare module.exports: $Exports<'underscore-contrib/test/util.existential'>;
}
declare module 'underscore-contrib/test/util.operators.js' {
  declare module.exports: $Exports<'underscore-contrib/test/util.operators'>;
}
declare module 'underscore-contrib/test/util.strings.js' {
  declare module.exports: $Exports<'underscore-contrib/test/util.strings'>;
}
declare module 'underscore-contrib/test/util.trampolines.js' {
  declare module.exports: $Exports<'underscore-contrib/test/util.trampolines'>;
}
declare module 'underscore-contrib/test/vendor/jquery.js' {
  declare module.exports: $Exports<'underscore-contrib/test/vendor/jquery'>;
}
declare module 'underscore-contrib/test/vendor/jslitmus.js' {
  declare module.exports: $Exports<'underscore-contrib/test/vendor/jslitmus'>;
}
declare module 'underscore-contrib/test/vendor/qunit.js' {
  declare module.exports: $Exports<'underscore-contrib/test/vendor/qunit'>;
}
declare module 'underscore-contrib/test/vendor/runner.js' {
  declare module.exports: $Exports<'underscore-contrib/test/vendor/runner'>;
}
declare module 'underscore-contrib/test/vendor/underscore.js' {
  declare module.exports: $Exports<'underscore-contrib/test/vendor/underscore'>;
}
declare module 'underscore-contrib/underscore.array.builders.js' {
  declare module.exports: $Exports<'underscore-contrib/underscore.array.builders'>;
}
declare module 'underscore-contrib/underscore.array.selectors.js' {
  declare module.exports: $Exports<'underscore-contrib/underscore.array.selectors'>;
}
declare module 'underscore-contrib/underscore.collections.walk.js' {
  declare module.exports: $Exports<'underscore-contrib/underscore.collections.walk'>;
}
declare module 'underscore-contrib/underscore.function.arity.js' {
  declare module.exports: $Exports<'underscore-contrib/underscore.function.arity'>;
}
declare module 'underscore-contrib/underscore.function.combinators.js' {
  declare module.exports: $Exports<'underscore-contrib/underscore.function.combinators'>;
}
declare module 'underscore-contrib/underscore.function.dispatch.js' {
  declare module.exports: $Exports<'underscore-contrib/underscore.function.dispatch'>;
}
declare module 'underscore-contrib/underscore.function.iterators.js' {
  declare module.exports: $Exports<'underscore-contrib/underscore.function.iterators'>;
}
declare module 'underscore-contrib/underscore.function.predicates.js' {
  declare module.exports: $Exports<'underscore-contrib/underscore.function.predicates'>;
}
declare module 'underscore-contrib/underscore.object.builders.js' {
  declare module.exports: $Exports<'underscore-contrib/underscore.object.builders'>;
}
declare module 'underscore-contrib/underscore.object.selectors.js' {
  declare module.exports: $Exports<'underscore-contrib/underscore.object.selectors'>;
}
declare module 'underscore-contrib/underscore.util.existential.js' {
  declare module.exports: $Exports<'underscore-contrib/underscore.util.existential'>;
}
declare module 'underscore-contrib/underscore.util.operators.js' {
  declare module.exports: $Exports<'underscore-contrib/underscore.util.operators'>;
}
declare module 'underscore-contrib/underscore.util.strings.js' {
  declare module.exports: $Exports<'underscore-contrib/underscore.util.strings'>;
}
declare module 'underscore-contrib/underscore.util.trampolines.js' {
  declare module.exports: $Exports<'underscore-contrib/underscore.util.trampolines'>;
}
